# Generated by Django 4.0.2 on 2023-08-27 14:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Court',
        ),
        migrations.DeleteModel(
            name='Lawyer',
        ),
        migrations.RenameField(
            model_name='lawcase',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='casecategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lawcase',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='casecategory',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casecategory',
            name='title',
            field=models.CharField(default='title', max_length=199),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lawcase',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lawcase',
            name='location',
            field=models.CharField(default='location', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casecategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lawcase',
            name='case_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.casecategory'),
        ),
        migrations.AlterField(
            model_name='lawcase',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
